## Case Study 1

1. ABCD is a parallelogram. A is (—1,2,1), B is (2,0, —1), and D is (3,1, 4). Using numpy.array in
Python,

a. Find the coordinates of C.

b. Calculate the angle A.

c. Calculate the area of the parallelogram.

In [1]:
#to find C cordinate, Given points A,B and D w/position vectors A(-1,2,1), B(2,0,-1) and D(3,1,4). Find vectors AB and AD then find point C with position vector c such that ABCD is a parallelogram.

#Use the same method no matter how many coordinates. Treat  a ,  b , and  d  as vectors themselves. (They’re the heads of vectors whose tails are at the origin.) Then

In [18]:
import numpy as np
A=np.array([-1,2,1])
B=np.array([2,0,-1])
D=np.array([3,1,4])

In [19]:
#a. Find the coordinates of C.
C=-A+B+D
C 

array([ 6, -1,  2])

In [20]:
#b. Calculate the angle A.
A_B = B-A
A_D = D-A
B_C = C-B
D_C = C-D

Dot_Product = np.dot(A_B,A_D)
Magnitude = (np.linalg.norm(A_B))*(np.linalg.norm(A_D))
Angle_A = np.arccos(Dot_Product/Magnitude)
print("The Angle A is",Angle_A,"radians")

The Angle A is 1.180436502424873 radians


In [21]:
#c. Calculate the area of the parallelogram.
vector_u=A-B
vector_v=A-C
Area=np.cross(vector_u,vector_v)

#take the magnitude of the vector Area
magnitude = np.linalg.norm(Area)
print("the area of the parallelogram =",magnitude)

the area of the parallelogram = 19.44222209522358


2. A car rental company owns 150 vehicles in total, including x of model X, y of model Y, and z of
model Z. In yard A there are 46 vehicles including 20% of the model X fleet,40% of the model Y
fleet, and 30% of the model Z fleet. In yard B there are 54 vehicles including 40% of the model X
fleet, 20% of the model Y fleet, and 50% of the model Z fleet. How many vehicles of each type
does the rental company have? You are required to use Python and Matrix form to find the
answer.

In [22]:
import numpy as np
#total=150
#A=46
#B=56
#total=x+y+z
#A=(0.2*x)+(0.4*y)+(0.3*z)
#B=(0.4*x)+(0.2*y)+(0.5*z)
#these are the three linear equations

In [23]:
#using numpy we create matrix as follows
a=np.array([[1,1,1],[0.2,0.4,0.3],[0.4,0.2,0.5]])
b=np.array([150,46,54])
k=np.array(["x","y","z"])
#here we will have as
#ak=b
#k=a'b where a' is adj(a)
#using numpy it has a predefined function known as np.linalg.solve() which does this math as defined above.

In [24]:
z=np.linalg.solve(a,b)
print("The owner has cars ads folllows\nModel X cars =",round(z[0]),"\nModel Y cars =",round(z[1]),"\nModel Z cars=",round(z[2]))

The owner has cars ads folllows
Model X cars = 45 
Model Y cars = 55 
Model Z cars= 50


3. Refer to Brownlee (2018)[1], using random number generator to generate two 3x3x3 tensors
(set seed to 99) and perform tensor addition, tensor subtraction, tensor Hadamard product and
tensor product respectively.

In [25]:
import random

In [26]:
A=random.seed(99)
A=np.random.random((3,3,3))
A=np.array(A)
B=random.seed(99)
B=np.random.random((3,3,3))
B=np.array(B)

In [27]:
print("A=",A)
print()
print("B=",B)

A= [[[0.33436642 0.13179212 0.24313104]
  [0.10938043 0.48591106 0.67528866]
  [0.3653256  0.10039253 0.91534143]]

 [[0.2775101  0.74451042 0.25775298]
  [0.89114705 0.45078932 0.27997629]
  [0.0434477  0.15708175 0.62204209]]

 [[0.41131101 0.18284788 0.58624445]
  [0.19011501 0.46907335 0.3124237 ]
  [0.02485108 0.25008958 0.72414052]]]

B= [[[0.50404458 0.85055876 0.02056823]
  [0.15260643 0.34374029 0.66462164]
  [0.04142279 0.43700227 0.54933715]]

 [[0.450197   0.7829823  0.44674715]
  [0.96291493 0.96511601 0.38259564]
  [0.45743102 0.94200645 0.09784137]]

 [[0.86726258 0.23840319 0.5377777 ]
  [0.21768339 0.37187226 0.52190476]
  [0.77376915 0.67058523 0.21418008]]]


In [28]:
#tensor addition
Sum=A+B
print("The tensor addition for two random A and B 3x3x3 matrix are\n\n",Sum)

The tensor addition for two random A and B 3x3x3 matrix are

 [[[0.838411   0.98235088 0.26369927]
  [0.26198685 0.82965134 1.3399103 ]
  [0.40674839 0.5373948  1.46467858]]

 [[0.7277071  1.52749273 0.70450013]
  [1.85406199 1.41590534 0.66257193]
  [0.50087872 1.0990882  0.71988347]]

 [[1.27857359 0.42125106 1.12402214]
  [0.4077984  0.84094561 0.83432845]
  [0.79862023 0.92067481 0.9383206 ]]]


In [29]:
#tensor substraction
Sub=A-B
print("the tensor substraction for two random A and B 3x3x3 matrix are\n\n",Sub)

the tensor substraction for two random A and B 3x3x3 matrix are

 [[[-0.16967816 -0.71876663  0.22256282]
  [-0.043226    0.14217077  0.01066702]
  [ 0.3239028  -0.33660974  0.36600428]]

 [[-0.1726869  -0.03847188 -0.18899416]
  [-0.07176788 -0.51432669 -0.10261935]
  [-0.41398332 -0.7849247   0.52420072]]

 [[-0.45595158 -0.05555531  0.04846675]
  [-0.02756838  0.09720109 -0.20948106]
  [-0.74891807 -0.42049565  0.50996044]]]


In [30]:
#tensor hadamard product
Multiply=A*B
print("the tensor hadamard product for two random A and B 3x3x3 matrix are\n\n",Multiply)

the tensor hadamard product for two random A and B 3x3x3 matrix are

 [[[0.16853558 0.11209694 0.00500077]
  [0.01669216 0.16702721 0.44881146]
  [0.01513281 0.04387176 0.50283105]]

 [[0.12493421 0.58293849 0.11515041]
  [0.85809881 0.43506399 0.10711771]
  [0.01987432 0.14797202 0.06086145]]

 [[0.35671465 0.04359152 0.31526919]
  [0.04138488 0.17443537 0.16305541]
  [0.019229   0.16770638 0.15509647]]]


4. Refer to Kumar(2020)[2], using Keras and MNIST dataset, print the information about the tensor
rank / axes and the shape of the train_images dataset.

In [31]:
import pandas as pd
from tensorflow import keras
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [32]:
train_images.shape

(60000, 28, 28)

In [33]:
train_images.ndim

3

The above code displays the fact that MNIST datset has axes 3 and shape of  60,000 matrices of 28×28 integers.